export { default as DeleteSuccess } from "./DeleteSuccess.jsx";
export { default as EditUser } from "./EditUser.jsx";
export { default as HaircutPrice } from "./HaircutPrice.jsx";
export { default as HaircutStatus } from "./HaircutStatus.jsx";
export { default as BarberList } from "./BarberList.jsx";
export { default as Create } from "./Create.jsx";
export { default as Menu } from "./Menu.jsx";
export { default as LogoutSuccess } from "./LogoutSuccess.jsx";
export { default as TimeToPay } from "./TimeToPay.jsx";
